[package]
name = "blp-lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
blp = "0.1.32"
libc = "0.2.177"

[package.metadata.crate-type]
cdylib = true
staticlib = true